name: Build Executable and Installer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Package with PyInstaller
      run: pyinstaller --onefile calculator.py

    - name: Download and Install Inno Setup
      shell: powershell
      run: |
        # Download Inno Setup (Quick Download link from official site)
        Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "innosetup.exe"
        # Install Inno Setup (non-interactive install)
        Start-Process -Wait -FilePath ".\innosetup.exe" -ArgumentList "/VERYSILENT /SP-"

    - name: Compile Inno Setup Script
      shell: powershell
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" calculator-installer.iss
      env:
        ProgramFiles(x86): 'C:\Program Files (x86)' # Needed for Inno Setup path

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculator-installer-exe
        path: ./InstallerOutput/SimpleCalculatorInstaller.exe # Path to the installer .exe
